deployment:
  tasks:
    - echo "Installing dependencies…"
    - pip install --upgrade pip
    - pip install -r requirements.txt

    - echo "Running migrations…"
    - python manage.py migrate --noinput

    - echo "Collecting static files…"
    - python manage.py collectstatic --noinput

    # Optional seeds / superuser:
    # - echo "Creating superuser…"
    # - python manage.py createsuperuser --noinput --username admin --email admin@example.com

    - echo "Restarting application…"
    - passenger-config restart-app $(pwd)
