# Generated by Django 5.1.6 on 2025-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='crypto_currency',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin'), ('BANK', 'Bank Transfer')], max_length=10, null=True),
        ),
    ]
